apiVersion: v1
name: joblib-dask-deadlock
version: 1.0
appVersion: 1.0
description: Minimal Reproducible Bug Example - dead lock in `joblib.Parallel._lock` when using `dask` as a back-end
home: https://github.com/jjerphan/joblib_dask_deadlock

maintainers:
- name: Julien Jerphanion (jjerphan)
  email: git@jjerphan.xyz
