apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "dask.fullname" . }}-worker
  labels:
    app: {{ template "dask.name" . }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "dask.chart" . }}
    component: worker
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      app: {{ template "dask.name" . }}
      release: {{ .Release.Name | quote }}
      component: worker
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ template "dask.name" . }}
        release: {{ .Release.Name | quote }}
        component: worker
    spec:
      containers:
        - name: {{ template "dask.fullname" . }}-worker
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          args:
            - {{ .Values.worker.entrypointArg }}
          ports:
            - containerPort: 8789
          env:
            - name: DASK_SCHEDULER_ADDRESS
              value: "{{ template "dask.fullname" . }}-server"
            - name: DASK_SCHEDULER_PORT
              value: "{{ .Values.server.servicePort }}"
