apiVersion: batch/v1
kind: Job
metadata:
  name: joblib-dask-deadlock-server
spec:
  backoffLimit: 0
  template:
    metadata:
    spec:
      containers:
      - name: c
        image: jjerphan/joblib_dask_deadlock:latest
        imagePullPolicy: Always
        env:
        - name: PYTHON_VERSION
          value: "python36"
        - name: PATH
        args: ["server"]
      restartPolicy: Never
